### ISSUE TITLE
ONTOLOGY uri assumed to be absolute

### ISSUE THREAD

**Issue by stain** [stain/owl2jsonld#3]
```
$java -jar owl2jsonld-0.2.1-standalone.jar -v EDAM_1.6.owl
Exception in thread "main" java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URI.toURL(URI.java:1088)
        at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.canLoad(ParsableOWLOntologyFactory.java:165)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:863)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:797)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at owlapi.core$load_ontology.invoke(core.clj:78)
        at clojure.core$map$fn__4245.invoke(core.clj:2557)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$dorun.invoke(core.clj:2855)
        at clojure.core$doall.invoke(core.clj:2871)
        at owl2jsonld.core$owl2jsonld.invoke(core.clj:134)
        at owl2jsonld.app$main.invoke(app.clj:64)
        at owl2jsonld.app$_main.doInvoke(app.clj:81)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at owl2jsonld.app.main(Unknown Source)
```

A workaround is to use `file:EDAM_1.6.owl` or `file:///home/stain/Desktop/EDAM_1.6.owl`

The fix should be to resolve URIs relative to file:/// path of the current directory.

**Comment by plonker1** [comment]
This would be a useful tool. I cannot get past the (silly?) 'URI is not absolute' thing. I've tried all combinations of suggested workarounds. My ontology is in a local file. Any more suggestions?

**Comment by stain** [comment]
I think this is owlapi who don't like relative references.

Try opening it as file:///users/John/ontology.ttl

Or add to the top of your ontology a @base http://example.com/ . (Or
equivalent xml:base="..." In RDF xml)

**Comment by BigBlueHat** [comment]
Thanks @stain! That worked for me.

PR to add that as an example option forthcoming. 😸

**Comment by Sobitan** [comment]
Hello All,
Thanks for sharing this response.
I was able to use this to solve a "uri is not absolute" error for the loadOntologyFromOntologyDocument method. Everything now works fine.
Thanks.
